name: 'Send dingding notice'
description: '发送钉钉服务发布消息'
inputs:
  notice-title:
    description: 消息卡片标题
    required: true
  notice-color:
    description: 消息卡片颜色
    required: true
  button-text:
    description: 按钮文本
    required: true
  button-link:
    description: 按钮链接
    required: true
  webhook-url:
    description: 飞书消息通知 webhook url
    required: true
  notice-markdown:
    description: 消息 markdown 内容
    required: true
runs:
  using: "composite"
  steps:
    - id: send-notice
      env:
        NOTICE_COLOR: ${{ inputs.notice-color }}
        WEBHOOK_URL: ${{ inputs.webhook-url }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        NOTICE_MARKDOWN: ${{ toJSON(inputs.notice-markdown) }}
      run: |
          NOTICE_TITLE="${{ inputs.notice-title }}"
          export TZ='Asia/Shanghai'
          DATE_TIME=$(date +'%Y-%m-%d %H:%M:%S')
          USE_NOTICE_MARKDOWN=`sed -e 's/^"//' -e 's/"$//' <<< $NOTICE_MARKDOWN`

          cat <<EOF > post-data.json
          {"msgtype":"markdown","markdown":{"title":"${NOTICE_TITLE}","text":"## <font color=${NOTICE_COLOR}>${NOTICE_TITLE}</font>\n-----\n ${USE_NOTICE_MARKDOWN} \n-------\n##### ${COMMIT_MESSAGE} \n-------\n \n###### $DATE_TIME \n"}}
          EOF
          cat post-data.json

          curl -X POST "${WEBHOOK_URL}" \
          --header 'Content-Type: application/json' \
          --data-raw "$(cat <<EOF
          {"msgtype":"markdown","markdown":{"title":"${NOTICE_TITLE}","text":"## <font color=${NOTICE_COLOR}>${NOTICE_TITLE}</font>\n-----\n ${USE_NOTICE_MARKDOWN} \n-------\n##### ${COMMIT_MESSAGE} \n-------\n \n###### $DATE_TIME \n"}}
          EOF
          )"
      shell: bash
      